#!/bin/sh

. ./utils

ws_name="tfe-test-workspace-$(random_enough)"

# create a new workspace without any options
output="$(tfe workspace new -name "$TFE_ORG/$ws_name" 2>&1)"
assert_equal "tfe_ws_new_noop_ret_0" 0 $?
assert_contains "tfe_ws_new_noop_has_created" "Created" "$output"

